### ISSUE TITLE
Site doesn't exist

### ISSUE THREAD

**Issue by UrsaPolarisRecords** [UrsaPolarisRecords/Polaris#5]
**Describe the bug**
Nobody has created the site yet

**To Reproduce**
1. Go to the internet
2. search google
3. it's not there

**Expected behavior**
It should be there

**Comment by lpbellier** [comment]
frghjkl;`comment

**Comment by lpbellier** [comment]
yosufsa fknaskjnfkasnfvkansvlknasl

**Comment by mellowjayb** [comment]
Work is done!

**Comment by mellowjayb** [comment]
Re-submitted!

**Comment by UrsaPolarisRecords** [comment]
I saw the site it looks awesome
