### ISSUE TITLE
Please groom my dog every 2 months

### ISSUE THREAD

**Issue by martybe** [UrsaPolarisRecords/Polaris#6]
#### User Story
As a _**[]**_, I would like _**[]**_ in order to _**[]**_.

#### Description
[insert additional feature/bug description, if available]

#### Solution
[add proposed solution, groomed feature description]

#### Design

- [ ] 

#### Smart Contract

- [ ] 

#### Backend

- [ ] 

#### Frontend

- [ ] 

#### Infrastructure

- [ ] 

#### Testing

- [ ] Test in DEV
- [ ] Test in PROD

#### Marketing

- [ ] 

#### Documentation

- [ ]

**Comment by martybe** [comment]
Where is ur work?

**Comment by mellowjayb** [comment]
Here!
![image](https://github.com/UrsaPolarisRecords/Polaris/assets/9080526/3c269a7b-d23f-48be-aeaf-7861ad5857ea)

**Comment by martybe** [comment]
That's way better. What took you so long.

**Comment by mellowjayb** [comment]
The internet was slow

**Comment by martybe** [comment]
Can you also dye his ears pink

**Comment by mellowjayb** [comment]
Please create another bounty for that!

**Comment by UrsaPolarisRecords** [comment]
Closed as completed
